# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-16 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160609_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
