# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def fowards(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    Category = apps.get_model('api', 'Category')

    for product in Product.objects.all():
        category_name = product.category_name
        if not category_name:
            category_name = 'Category of ' + product.name

        category = Category(name=category_name, description='')
        category.save()

        product.category = category
        product.save()



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_category'),
    ]

    operations = [
        migrations.RunPython(fowards),
    ]
