# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Rejected'), (2, 'Aproved')], default=0),
        ),
    ]
